---
os: osx
osx_image:
# OS X 10.15
  - xcode12
# OS X 10.14
  - xcode11.2

language: python
python: '3.6'
sudo: required
install:
  - pip install --upgrade pip
  - pip install ansible
env:
  global:
    - TEST_ANSIBLE_HOSTNAME: localhost
      TEST_ANSIBLE_CONNECTION: local
script:
  - ansible-playbook -i test/inventory test/playbook.yml --syntax-check
  - ansible-playbook -i test/inventory test/playbook.yml --list-tasks
  - ansible-playbook -i test/inventory test/playbook.yml --connection=local --become -vvvv
  - 'ansible-playbook -i test/inventory test/playbook.yml --connection=local --become | grep -q "changed=0.*failed=0" &&
    (echo "Idempotence test: pass" && exit 0) || (echo "Idempotence test: fail" && exit 1)'
...
