---
language: python
python: '3.8.5'
sudo: required
addons:
  apt:
    sources:
      - python-apt
      - python-pycurl
install:
  - pip install --upgrade pip
  - pip install ansible
env:
  global:
    - TEST_ANSIBLE_HOSTNAME: localhost
      TEST_ANSIBLE_CONNECTION: local
script:
  - ansible-playbook -i tests/inventory tests/playbook.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/playbook.yml --list-tasks
  - ansible-playbook -i tests/inventory tests/playbook.yml --become -vvvv
  - 'ansible-playbook -i tests/inventory tests/playbook.yml --become | grep -q "changed=0.*failed=0" &&
    (echo "Idempotence test: pass" && exit 0) || (echo "Idempotence test: fail" && exit 1)'
...
